[package]
name = "pneuma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default-features = []
full = ["io"]
io = []
unsafe_work_stealing = []

[dependencies]
crossbeam-deque = "0.8.5"
dns-protocol = "0.1.1"
fastrand = "2.1.0"
libc = "0.2.151"
memchr = "2.7.2"
mio = { version = "0.8.10", features = ["os-poll", "net"] }
slab = "0.4.9"
thread_local = "1.1.8"
tokio = { version = "1.37.0", features = ["net", "rt"] }


[target.'cfg(target_os="linux")'.dependencies]
io-uring = "0.6.2"

[dev-dependencies]
pneuma = { path = ".", features = ["full", "unsafe_work_stealing"] }
rand = "0.8.5"
